// <auto-generated />
using System;
using EventManager.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventManager.Migrations
{
    [DbContext(typeof(EventManagerDbContext))]
    [Migration("20260420145210_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EventManager.EventRepeat.EventRepeatInfo", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("DaysOfWeekPattern")
                        .HasColumnType("longtext");

                    b.Property<int>("ForwardTime")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfWeeksToGenerate")
                        .HasColumnType("int");

                    b.Property<bool>("Repeat")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("TargetDayOfWeek")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.ToTable("RepeatInfo");
                });

            modelBuilder.Entity("EventManager.Events.Models.DiscordEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutomaticallyCreated")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<ulong?>("EventChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("EventId")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("Expired")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("InviteUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("ThreadChannelId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EventManager.Events.Models.EventUserInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("UserEventInterest");
                });

            modelBuilder.Entity("EventManager.GuildConfiguration.GuildConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong?>("EventChannel")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int?>("ThreadKeepAliveTime")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("ThreadRefreshTime")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.ToTable("GuildConfiguration");
                });

            modelBuilder.Entity("EventManager.EventRepeat.EventRepeatInfo", b =>
                {
                    b.HasOne("EventManager.Events.Models.DiscordEvent", "Event")
                        .WithOne("RepeatInfo")
                        .HasForeignKey("EventManager.EventRepeat.EventRepeatInfo", "EventId");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventManager.Events.Models.EventUserInterest", b =>
                {
                    b.HasOne("EventManager.Events.Models.DiscordEvent", "Event")
                        .WithMany("InterestedUsers")
                        .HasForeignKey("EventId");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventManager.Events.Models.DiscordEvent", b =>
                {
                    b.Navigation("InterestedUsers");

                    b.Navigation("RepeatInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
